// post a blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "The Road to React",
  "author": "Robin Wieruch",
  "url": "https://www.roadtoreact.com/",
  "likes": 100
  }

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "The Art of War",
  "author": "Sun Tzu",
  "url": "https://www.amazon.com/Art-War-Sun-Tzu/dp/1599869772",
  "likes": 89
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "test123",
  "name": "test",
  "password": "password"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "The Subtle Art of Not Giving a F*ck",
  "author": "Mark Manson",
  "url": "https://www.amazon.com/Subtle-Art-Not-Giving-Counterintuitive/dp/0062457713",
  "likes": 69,
  "user": "6280dd4df6b8b14d670497da"
}