// post a blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "The Art of War",
  "author": "Sun Tzu",
  "url": "https://www.amazon.com/Art-War-Sun-Tzu/dp/1599869772",
  "likes": 89
}
